name: Upload S3
  uses: shallwefootball/upload-s3-action@v1.1.3
  with:
    # aws key id
    aws_key_id: AKIAYMO4EOGRCZFRBCPP
    # aws secret access key
    aws_secret_access_key: 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
    # aws bucket name
    aws_bucket: socialmediawriter
    # directory to upload
    source_dir: clairenicholson078.github.io
    # destination directory for upload
    destination_dir: # optional, default is /
